"""
Django settings for iscoutyou project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'q5=3uu)_y8ibgt9s7n*r2t%py5(mk6&uufyw9w-xs^kh1q25ff'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = (
    'flat',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'registration',
    'bootstrap3',
    'bootstrap_pagination',
    #'allauth',
    #'allauth.account',
    #'allauth.socialaccount',
    'administrator',
    'base',
    'athletes',
    'scouts',
    'sports',
    'university',
    'django.contrib.humanize',
    'embed_video',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'athletes.middleware.AutoLogout',
)

ROOT_URLCONF = 'iscoutyou.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates/admin_iscoutyou')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'iscoutyou.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'iscout10_recruitment',
         'USER': 'root',
         'PASSWORD': 'root',
         'HOST': '127.0.0.1',
         'PORT': '3306',
     }
 }




# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = False 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
#STATIC_ROOT = '/Users/joseantoniolopezperez/Desktop/iScoutyou/static/'
#MEDIA_ROOT = '/Users/joseantoniolopezperez/Desktop/iScoutyou/static/images/'

#STATIC_URL = '/Users/joseantoniolopezperez/Desktop/iScoutyou/static/'
#MEDIA_URL = '/Users/joseantoniolopezperez/Desktop/iScoutyou/static/images/'

try:
    from local_settings import *
except ImportError as e:
    pass

# try:
#     from bootstrap3_settings import *
# except ImportError as e:
#     pass


SITE_ID = 1

ACCOUNT_ACTIVATION_DAYS = 1
REGISTRATION_AUTO_LOGIN = True


# Configuracion servidor de correo somoscodigo.com.ve

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 

# DEFAULT_FROM_EMAIL = 'desarrollopruebas@somoscodigo.com.ve'
# EMAIL_HOST_USER = 'desarrollopruebas@somoscodigo.com.ve'
# EMAIL_HOST_PASSWORD = 'Temporal2021'
# EMAIL_USE_TLS = False 
# EMAIL_PORT = 26

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
AUTO_LOGOUT_DELAY = 15
